unzipped_path: /home/bigbrainman/APDS-final-project/data/unzipped

cache_dir: /home/bigbrainman/APDS-final-project/data/cache

split_path: datasets/split.json

split:
  train: 100
  val: 10
  test: 20

slice_number: 5

img_size: 512

clip_lower: -200
clip_upper: 200

optimizer: adam

n_res_blocks: 2

batch_size: 8

n_classes: 3

dim_mults: 
  - 1
  - 2
  - 4
  - 8
  # - 16

mask_classes:
  empty: 0
  liver: 1
  cancer: 2

attn_heads: 4

attn_head_dim: 32

