unzipped_path: /home/bigbrainman/APDS-final-project/data/unzipped

cache_dir: /home/bigbrainman/APDS-final-project/data/cache

checkpoint_dir: /home/bigbrainman/APDS-final-project/checkpoints

train_log_file_iters: /home/bigbrainman/APDS-final-project/iters_train.csv

train_log_file_epochs: /home/bigbrainman/APDS-final-project/epochs_train.csv

split_path: datasets/split.json

split:
  train: 100
  val: 10
  test: 20

clip_lower: -200
clip_upper: 200

n_res_blocks: 2

batch_size: 8
dataloader_num_workers: 4

n_classes: 3

dim_mults: 
  - 1
  - 2
  - 4
  - 8
  # - 16

learning_rate: 0.001

loss_weights:
  - 0.1
  - 0.7
  - 3

mask_classes:
  empty: 0
  liver: 1
  cancer: 2

attn_heads: 4

attn_head_dim: 32

log_every_iter: 1
log_every_epoch: 1

save_every_iter: 300