unzipped_path: /media/bigbrainman/DataDrive/data/LITS17/unzipped

cache_dir: /media/bigbrainman/DataDrive/data/LITS17/cache

zipped_path: /media/bigbrainman/DataDrive/data/LITS17

split_path: datasets/split.json

split:
  train: 100
  val: 10
  test: 20

slice_number: 5

img_size: 512

clip_lower: -45
clip_upper: 105


n_res_blocks: 3

n_classes: 3

dim_mults: 
  - 1
  - 2
  - 4
  - 8
  - 16

attn_heads: 4

attn_head_dim: 32

