unzipped_path: /media/bigbrainman/DataDrive/data/LITS17/unzipped

cache_dir: /media/bigbrainman/DataDrive/data/LITS17/cache

zipped_path: /media/bigbrainman/DataDrive/data/LITS17

split_path: datasets/split.json

split:
  train: 100
  val: 10
  test: 20

slice_number: 5

img_size: 512

clip_lower: -45
clip_upper: 105

optimizer: adam

n_res_blocks: 2

batch_size: 8

n_classes: 3

dim_mults: 
  - 1
  - 2
  - 4
  - 8
  # - 16

mask_classes:
  empty: 0
  liver: 1
  cancer: 2

attn_heads: 4

# attn_head_dim: 32

