unzipped_path: /media/bigbrainman/DataDrive/data/LITS17/unzipped

cache_dir: /media/bigbrainman/DataDrive/data/LITS17/cache

zipped_path: /media/bigbrainman/DataDrive/data/LITS17

split_path: datasets/split.json

split:
  train: 100
  val: 10
  test: 20

slice_number: 5

n_res_blocks: 3

n_classes: 3

dim_mults: 
  - 1
  - 2
  - 4

attn_heads: 4

attn_head_dim: 32

